# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
- name: one
  value: initialValue 
  
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
- script: |
    echo ${{ variables.one }} # outputs initialValue
    echo $(one)
  displayName: First variable pass
- bash: echo '##vso[task.setvariable variable=one]secondValue'
    displayName: Set new variable value
- script: |
    echo ${{ variables.one }} # outputs initialValue
    echo $(one) # outputs secondValue
  displayName: Second variable pass
